//! Conversation state: message history, roles, and usage tracking.
//!
//! A [`Conversation`] holds an ordered list of [`Message`] items, each with
//! a [`Role`] (user or assistant). The orchestrator maintains parallel ZH and
//! EN conversations so both sides of the bridge are recorded for analysis.

use serde::{Deserialize, Serialize};

/// Who sent a message.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    /// The human user's turn.
    User,
    /// Claude's turn.
    Assistant,
}

/// A single message in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who sent this message.
    pub role: Role,
    /// The message body.
    pub content: String,
}

/// Ordered conversation history with an optional system prompt.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Conversation {
    /// An optional system prompt prepended to every turn (used by the API backend).
    pub system: Option<String>,
    /// The ordered list of user/assistant messages.
    pub messages: Vec<Message>,
}

impl Conversation {
    /// Create a new empty conversation with no system prompt.
    ///
    /// # Example
    ///
    /// ```rust
    /// use sigo_core::conversation::Conversation;
    /// let convo = Conversation::new();
    /// assert!(convo.messages.is_empty());
    /// ```
    pub fn new() -> Self {
        Self::default()
    }

    /// Create a new conversation with a system prompt.
    pub fn with_system(system: impl Into<String>) -> Self {
        Self {
            system: Some(system.into()),
            messages: vec![],
        }
    }

    /// Append a user message.
    pub fn push_user(&mut self, content: impl Into<String>) {
        self.messages.push(Message {
            role: Role::User,
            content: content.into(),
        });
    }

    /// Append an assistant message.
    pub fn push_assistant(&mut self, content: impl Into<String>) {
        self.messages.push(Message {
            role: Role::Assistant,
            content: content.into(),
        });
    }

    /// Return the last user message, if any.
    pub fn last_user(&self) -> Option<&str> {
        self.messages
            .iter()
            .rev()
            .find(|m| m.role == Role::User)
            .map(|m| m.content.as_str())
    }
}

/// Which Claude backend is being used.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum BackendKind {
    /// Anthropic Messages API (default).
    Api,
    /// Local `claude` CLI process (Claude Code).
    ClaudeCode,
}

/// Translation direction.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum Direction {
    /// English → Chinese.
    EnToZh,
    /// Chinese → English.
    ZhToEn,
}

/// Token usage reported by Claude for one turn.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Usage {
    /// Input tokens consumed by this turn.
    pub input_tokens: u32,
    /// Output tokens generated by this turn.
    pub output_tokens: u32,
    /// Prompt cache read tokens (API backend).
    pub cache_read: Option<u32>,
    /// Prompt cache write tokens (API backend).
    pub cache_write: Option<u32>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn push_and_last_user() {
        let mut c = Conversation::new();
        c.push_user("hello");
        c.push_assistant("hi");
        c.push_user("again");
        assert_eq!(c.last_user(), Some("again"));
        assert_eq!(c.messages.len(), 3);
    }

    #[test]
    fn with_system_sets_system() {
        let c = Conversation::with_system("you are a translator");
        assert_eq!(c.system.as_deref(), Some("you are a translator"));
        assert!(c.messages.is_empty());
    }
}
